config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :posts, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:show, :edit, :update, :create, :destroy]
  end
  get '/profile', to: 'profiles#show', as: :profile
  get '/profile/edit', to: 'profiles#edit', as: :edit_profile
  patch '/profile', to: 'profiles#update', as: :update_profile

  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
  acts_as_voter
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validates :summary, presence: true
  validates :post_content, presence: true
  has_attachments :photos, maximum: 5
  has_attachments :video, maximum: 1
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :posts
   has_many :comments
   has_attachment :avatar
   after_create :send_welcome_email
   acts_as_voter

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @comments = policy_scope(Comment)
  end

  def show

  end

  def new

  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @post
    else
      flash.now[:danger] = "error"
    end

  end

  def edit
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def update
    @comment = Comment.find(params[:id])
    @post = @comment.post
    authorize @comment
    authorize @post
    if @comment.update_attributes(comment_params)
      redirect_to @post
    else
      render :action => "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    authorize @comment
    redirect_to post_path(@post)
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorised to complete this action"
    redirect_to(request.referrer || root_path)
  end

  def set_post
    @post = Post.find(params[:post_id])
    authorize @post
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  skip_before_action :authenticate_user!, only: [ :index, :show ]


  def index
    @posts = policy_scope(Post).order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post = @post
    authorize Comment
    authorize Post
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
      @post = Post.new(post_params)
      authorize @post
    if @post.save
      redirect_to @post
    else
      render :edit
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render "posts/show"
    end
    authorize @post
  end


  def destroy
  end


  private


  def user_not_authorized
    flash[:alert] = "You are not authorised to complete this action"
    redirect_to(request.referrer || root_path)
  end

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :post_content, :summary, photos: [], video: [])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    authorize current_user
  end

  def edit
    authorize current_user
  end

  def update
    authorize current_user
    if current_user.update(profile_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Comment</h1>
      <%= simple_form_for([@post, @comment]) do |f| %>
        <%= f.input :content, placeholder: "Enter a title" %>
        <%= f.submit class: "btn btn-danger"%>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Comment</h1>
      <%= simple_form_for([@post, @comment]) do |f| %>
        <%= f.input :content, placeholder: "Enter a title" %>
        <%= f.submit class: "btn btn-danger"%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" href="<%= image_path "favicon.ico" %>" type="image/ico" />
  <meta name="description" content="Red not Blue is a blog focussing on left wing politics and current affairs">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><%= content_for?(:title) ? yield(:title) : "Red not Blue" %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cosmo/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta property="og:title" content="Red not Blue" />
  <meta property="og:type" content="post" />
  <meta property="og:url" content="http://rednotblue.co.uk" />
  <meta property="og:image" content="https://i.ytimg.com/vi/zt6WdnrAvpE/maxresdefault.jpg" />
  <meta property="og:description" content="Red not Blue, a blog dedicated left wing politics and current affairs" />
  <meta property="og:site_name" content="Red not Blue" />


  <meta name="twitter:card" content="Red not Blue">
  <meta name="twitter:site" content="http://rednotblue.co.uk">
  <meta name="twitter:title" content="Red not Blue">
  <meta name="twitter:description" content="Red not Blue is a blog focussing on left wing politics and current affairs">
  <meta name="twitter:creator" content="">
  <meta name="twitter:image:src" content="https://i.ytimg.com/vi/zt6WdnrAvpE/maxresdefault.jpg">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-container">
  <div class="container">
    <div class="banner banner-top banner-gradient text-center" style="background-image: linear-gradient(-200deg, rgba(145,0,65,0.8) 0%, rgba(141,0,15,0.6) 0%), url('https://i.ytimg.com/vi/zt6WdnrAvpE/maxresdefault.jpg');">

        <div class="banner-gradient-shadow"></div>
          <div class="banner-content banner-font">
            <h1>
              [Enter Head]
            </h1>
            <p>
              <strong>[Enter tagline]</strong>.
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="container padded">
      <div class="row">
        <div class="text-center">
          <%= link_to t(".top_call_to_action", default: "Continue to Blog"), posts_path, class: "text-center btn-default btn" %>
        </div>
      </div>
    </div>

app/views/posts/_card.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('post.photo_url');">
        <div class="card-category"><%= post.created_at.strftime("Posted %a %m %b %Y at %H:%M")  %></div>
          <div class="card-description">
            <h2><%= post.title %></h2>
            <p><%= post.summary %></p>
          </div>
          <% if policy(Post).show? %>
          <%= link_to "", post_path(post), class: "card-link"%>
          <% end %>
      </div>
       <% if policy(Post).edit? %>
       <%= link_to "Edit", edit_post_path(post), :class => "btn btn-default" %>
       <% end %>
    </div>
  </div>
</div>

app/views/posts/_comment.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="comment-card">
        <div class="card-category list-inline">
          <% if policy(Post).edit? %>
          <%= link_to "Delete", post_comment_path(@post, comment), :class => "btn btn-danger",
            method: :delete,
            data: { confirm: "Are you sure?" } %>
          <% end %>
          <% if policy(Post).edit? %>
          <%= link_to "Edit", edit_post_comment_path(@post, comment), :class => "btn btn-success" %>
          <% end %>
          <p><%= comment.created_at.strftime("Posted %a %m %b %Y at %I:%M%p by") %>
            <%= comment.user.username %>
            <% if comment.user.avatar? %>
           <%= cl_image_tag comment.user.avatar.path, class: "avatar" %>
          <% end %>
          </p>
        </div>
          <div class="card-description">
          <p><%= comment.content  %></p>
          <% #if policy(Comment).destroy? %>

            <!-- <p><%=  %></p> -->
          </div>
          <!-- <img class="card-user avatar" src="user.jpg"> -->
          <%#= link_to "", post_path(post), class: "card-link"%>
      </div>
    </div>
  </div>
</div>

app/views/posts/_data.html.erb
<% if @post.photos.first %>
  <% main_post_photo = cl_image_tag @post.photos.first.path %>
<% else %>
  <% main_post_photo = "" %>
<% end %>

<% if @post.video.first %>
  <% main_post_video = cl_video_tag(@post.video.first.path, options = {:width => 700, :height => 400, :crop => :scale, :preload => "none", :controls => true, :fallback_content => "Your browser does not support HTML5 video tags"}) %>
<% else %>
  <% main_post_video = "" %>
<% end %>



<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= main_post_video %>
      <%= main_post_photo %>
      <!-- <div class="img-responsive" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.0) 100%, rgba(0,36,61,0.0) 100%), url('<%= main_post_photo %>') ;">
      </div> -->



      <div class="lead col-xs-12">
        <p><%= simple_format(@post.post_content) %></p>
      </div>
    </div>
  </div>
</div>

app/views/posts/_media.html.erb
<div class="media">
  <div class="col-xs-12">
    <div class="media-body">
    </div>
    <div class="media-section">
    </div>
    <div class="media-section">
  </div>
  <div class="media-aside">
    <div class="media-section">
      <h4 style="color: #8D0002">Share this story</h4>
      <%= render "posts/share" %>
    </div>
    <div class="media-section">
      <h2></h2>
    </div>
  </div>
</div>
</div>

app/views/posts/_share.html.erb
<%= social_share_button_tag(@post.title) %>

<!--
<div class="share-links">
<%= social_share_button_tag(@post.title) %>
  <a href="#" class="share-link bg-facebook">
    <i class="fa fa-facebook"></i>
  </a>
  <a href="#" class="share-link bg-twitter">
    <i class="fa fa-twitter"></i>
  </a>
  <a href="#" class="share-link bg-email">
    <i class="fa fa-envelope-o"></i>
  </a>
  <a href="#" class="share-link bg-text">
    <i class="fa fa-mobile"></i>
  </a>
</div>
 -->

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Post</h1>
      <%= simple_form_for @post do |f| %>
        <%= f.input :title, placeholder: "Enter a title" %>
        <%= f.input :summary, placeholder: "Short summary of post" %>
        <%= f.input :post_content, as: :text %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.input :video, as: :attachinary %>
        <%= f.submit class: "btn btn-default"%>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="banner-container">
  <div class="container">
    <div class="banner banner-top banner-gradient text-center" style="background-image: linear-gradient(-200deg, rgba(145,0,65,0.8) 0%, rgba(141,0,15,0.6) 0%), url('https://i.ytimg.com/vi/zt6WdnrAvpE/maxresdefault.jpg');">

        <div class="banner-gradient-shadow"></div>
          <div class="banner-content banner-font">
            <h1>
              [Enter Title]
            </h1>
            <p>
              <strong>[Enter Tagline]</strong>.
            </p>
          </div>
        </div>
      </div>
    </div>

<div class="container">
  <div class="row">
    <% @posts.each do |p| %>
    <%= render "card", post: p %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= simple_form_for(@post) do |f| %>
        <%= f.input :title, placeholder: "Enter a title" %>
        <%= f.input :summary, placeholder: "Short summary of post" %>
        <%= f.input :post_content %>
        <%= f.input :photos, as: :attachinary %>
        <%= f.input :video, as: :attachinary %>
        <%= f.submit class: "btn btn-default"%>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title) do %>
  <%= @post.title %>
<% end %>

<div class="banner-post" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('background.jpg');">
  <div class="banner-content">
    <h1><%= @post.title %></h1>
    <h2><%= @post.summary %></h2>
  </div>
</div>

<div class="container padded">
  <div class="row">
    <%= render "posts/data"%>
  </div>
</div>


<div class="container">
  <div class="row">
    <%= render "posts/media" %>
  </div>
</div>



<div class="container">
  <div class="row">
    <% @post.comments.each do |c| %>
    <%= render "posts/comment", comment: c %>
    <% end %>
  </div>
</div>


<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-lg-6">
    <%= simple_form_for [@post, @comment] do |f| %>
    <%= f.input :content, as: :text, label: "Post reply" %>
    <%= f.submit "Add comment", class: "btn btn-default" %>
    <% end %>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<!-- profile edit -->

<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-3">
      <%= simple_form_for(current_user, url: update_profile_path) do |f| %>
      <%= f.error_notification %>
      <%= f.input :username, placeholder: "Username" %>
      <%= f.input :first_name, placeholder: "First name" %>
      <%= f.input :last_name, placeholder: "Last name" %>
      <%= f.input :email, placeholder: "bob@bob.com" %>
      <%= f.input :avatar, as: :attachinary %>
      <%= f.error :base %>
      <div style="text-align: right;">
      <%= f.submit "Save", class: "btn btn-default"  %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<!-- <script>
  function submitForm() {
     // Get the first form with the name
     // Hopefully there is only one, but there are more, select the correct index
     var frm = document.getElementsByName('contact-form')[0];
     frm.submit(); // Submit
     frm.reset();  // Reset
     return false; // Prevent page refresh
  }
</script>
 -->

app/views/profiles/show.html.erb
<!-- PROFILE TEXT -->
<div class="container">
  <div class="row">
    <div class="col-md-12 col-sm-offset-4">
    <h1>Profile Page</h1>
    <% if current_user.avatar? %>
      <%= cl_image_tag current_user.avatar.path, class: "avatar-square" %>
    <% end %>
      <h4>Username: <%= current_user.username %></h4>
      <h4>First Name: <%= current_user.first_name %></h4>
      <h4>Last name: <%= current_user.last_name %></h4>
      <p>Email address: <%= current_user.email %></p>
      <%= link_to "Edit profile", edit_profile_path, class: "btn btn-default" %>
      <% if current_user.admin? %>
        <%= link_to t(".top_call_to_action", default: "New Post"), new_post_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to posts_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "favicon.ico" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>



      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag current_user.avatar.path, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
 <!-- <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>